# Generated by Django 5.1.4 on 2024-12-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('name', models.TextField()),
                ('last_price', models.FloatField()),
                ('market_cap', models.IntegerField()),
                ('country', models.TextField()),
                ('sector', models.TextField()),
                ('industry', models.TextField()),
            ],
        ),
    ]
