# Generated by Django 5.1.4 on 2025-01-04 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('open', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('ema_112', models.FloatField(blank=True, null=True)),
                ('ema_224', models.FloatField(blank=True, null=True)),
                ('ema_448', models.FloatField(blank=True, null=True)),
                ('ema_672', models.FloatField(blank=True, null=True)),
                ('macd', models.FloatField(blank=True, null=True)),
                ('macd_signal', models.FloatField(blank=True, null=True)),
                ('macd_diff', models.FloatField(blank=True, null=True)),
                ('rsi_14', models.FloatField(blank=True, null=True)),
                ('bollinger_high', models.FloatField(blank=True, null=True)),
                ('bollinger_low', models.FloatField(blank=True, null=True)),
                ('stochastic_k', models.FloatField(blank=True, null=True)),
                ('stochastic_d', models.FloatField(blank=True, null=True)),
                ('psar', models.FloatField(blank=True, null=True)),
                ('obv', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['ticker', 'date'],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
